name: Deploy Angular App # Name of the workflow

on:
  push:
    branches:
      - main # Runs this workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # The environment where the job runs (Linux)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Pulls the latest code from GitHub

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Uses Node.js version 18

      - name: Install dependencies
        run: npm ci # Installs project dependencies

      - name: Build Angular app
        run: npm run build -- --configuration=production # Builds the app in production mode

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist/sample-app # Saves the build output as an artifact
